Logger_code_Base/force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Custom log object used for apex logging.</description>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Logger_code_Base/force-app/main/default/objects/Log__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Stores the name of the Apex class where a log event occurred.</description>
    <label>Class</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Logger_code_Base/force-app/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>The severity level of the log entry (e.g., ERROR, WARN).</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Logger_code_Base/force-app/main/default/objects/Log_Event__e/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>The type of the Apex exception that was logged.</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Logger_code_Base/force-app/main/default/objects/Log_Event__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>he severity level of the log entry</description>
    <label>Level</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Logger_code_Base/force-app/main/default/objects/Log_Event__e/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>The line number of code where the logging happens</description>
    <label>Line Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Logger_code_Base/force-app/main/default/objects/Log_Event__e/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>The name of the method where a log event occurred.</description>
    <label>Method</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Logger_code_Base/force-app/main/default/objects/Log_Event__e/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Related record id of the logging if applicable</description>
    <label>RecordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Logger_code_Base/force-app/main/default/objects/Log_Event__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Stack trace for standard exceptions</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Logger_code_Base/force-app/main/default/classes/LogEventTriggerHandler.cls
/* @description
 * This Apex class handles the processing of Log_Event__e platform events. It listens for new events and creates corresponding Log__c records in Salesforce to store the details of each log event.
 * The class is designed to be efficient and scalable, allowing for bulk processing of events. It constructs the log name based on the class and method where the error occurred, and captures all relevant information such as the log level, record ID, line number, message, stack trace, and exception type.
 * The logs are inserted into the database in bulk to optimize performance, and the class is marked with "with sharing" to ensure that it respects the organization's sharing rules and security settings.
 * @author Naveen Rathod
 * @date 08-04-2026
 */
public with sharing class LogEventTriggerHandler {
  /**
   * @description This method is triggered when new Log_Event__e platform events are received.
   * It processes each event, constructs a log name, and creates a new Log__c record with the details from the event.
   * The method uses bulk processing to handle multiple events efficiently,
   * and it inserts the new log records into the database in a single operation to optimize performance.
   * @param newEvents A list of Log_Event__e events that have been received and need to be processed.
   */
  public static void handleEvents(List<Log_Event__e> newEvents) {
    List<Log__c> logsToInsert = new List<Log__c>();

    for (Log_Event__e event : newEvents) {
      String logName = 'Error in ' + event.Class__c + '.' + event.Method__c;

      logsToInsert.add(
        new Log__c(
          Class__c = event.Class__c,
          Exception_Type__c = event.Exception_Type__c,
          Level__c = event.Level__c,
          Line_Number__c = event.Line_Number__c,
          Message__c = event.Message__c,
          Method__c = event.Method__c,
          Name = logName.left(80),
          RecordId__c = event.RecordId__c,
          Stack_Trace__c = event.Stack_Trace__c
        )
      );
    }

    if (!logsToInsert.isEmpty()) {
      Database.insert(logsToInsert, false);
    }
  }
}